### ISSUE TITLE
Unity.Abstractions?

### ISSUE THREAD

**Issue by okonomiyaki3000** [vany0114/EF.DbContextFactory#14]
I'm using the Unity version. When I try to use `container.AddDbContextFactory<...>()`, I get an error like "The type IUnityContainer is defined in an assembly that is not referenced. You must add a reference to assembly 'Unity.Abstractions yadda yadda yadda'"

Any idea what I could be doing wrong?

**Comment by okonomiyaki3000** [comment]
Ah, I see... It requires version 2.2.0.0? Can that be right? My version is much newer for some reason.

**Comment by vany0114** [comment]
@okonomiyaki3000  Sorry for the very delayed answer but somehow I missed it. Did you manage to figure that out?

**Comment by okonomiyaki3000** [comment]
@vany0114 nope. I gave up and didn't use DbContextFactory.
